### ISSUE TITLE
Vis error

### ISSUE THREAD

**Issue by serhannn** [vadimkantorov/mpegflow#1]
Hi, I have tried `vis` both by building manually from source and using the provided binaries.

With the binaries I built from the source, I get the following output when I try out the `mpi_sintel_final_alley_1.avi` example provided in the `examples` directory:

```
$ ./mpegflow examples/mpi_sintel_final_alley_1.avi | ./vis examples/mpi_sintel_final_alley_1.avi
Skipping frame 2.
Skipping frame 3.
Skipping frame 4.
Skipping frame 5.
Skipping frame 6.
Skipping frame 7.
Skipping frame 8.
Skipping frame 9.
Skipping frame 10. 
:
:
```

I only see the output for the first frame and it continues like this until the end of the video.

When I use the provided binaries for `vis`, I get the following error:

```
vis: vis.cpp:91: std::pair<cv::Mat, int> read_flow(): Assertion `scanf("%d ", &flowComponents[k].at<int>(i, j)) == 1' failed.
Aborted (core dumped)
```

I also tried with other videos and get similar outputs in both cases. I appreciate any help.

**Comment by vadimkantorov** [comment]
Hi,
I'm also fighting a similar issue: https://github.com/Itseez/opencv/issues/5088

It may be that you need to compile vis with old FFmpeg 1.1.2 (put along compiled binary of mpegflow, and only then fix install_ffmpeg_here.sh to use 1.1.2, then recompile vis)

**Comment by SerhanGul** [comment]
Thanks, I will try that solution.
I also agree that there might be a bug (or a point which we are
overlooking) in the interface of OpenCV and FFmpeg.

**Comment by vadimkantorov** [comment]
Looking at it again, it's weird. Because that bug will just cause vis to not do anything, and not output "skipping frame" message. Let me know when you get if you do the recompiling feat.

**Comment by zbwglory** [comment]
Hi @SerhanGul  @vadimkantorov . This bug can be solved by changing the vis command to ./vis --occupancy examples/mpi_sintel_final_alley_1.avi

**Comment by aurotripathy** [comment]
@zbwglory, your comment (about using the occupancy flag) helped. Thank you.

I'm curious if anyone is using this technique (mpeg motion vector flow) instead of the other classical optical-flow techniques. 
Thank you
