### ISSUE TITLE
make

### ISSUE THREAD

**Issue by kuca2002** [vadimkantorov/mpegflow#11]
after i installed ffmpeg and opencv then i type cd .. and make and then this error comes 
![screen shot 2016-10-23 at 11 13 14](https://cloud.githubusercontent.com/assets/23016533/19628403/d6f60950-9911-11e6-9253-ae9bce628c5b.png)

**Comment by vadimkantorov** [comment]
You may need to install bzip2 and zlib, if they are not available on your system. Could you `locate libbz2.so`? Maybe just add them to `-L/path/to/dir/that/contains/libbz2.so`

**Comment by kuca2002** [comment]
okay thanks i just fixed it with 'sudo apt-get install libbz2-dev'

**Comment by kuca2002** [comment]
but i got another problem 
![screen shot 2016-10-24 at 20 39 04](https://cloud.githubusercontent.com/assets/23016533/19672327/4e505c76-9a2a-11e6-88f0-dac440802ee8.png)

**Comment by vadimkantorov** [comment]
Make sure OpenCV 3.1 is installed and visible. What does your `dependencies/include` list?
```
kantorov@gpu101:~$ ls $(wigwam status --path)/prefix/include/opencv2
calib3d      cvconfig.h      flann.hpp    imgcodecs.hpp  ml.hpp         opencv_modules.hpp  shape.hpp      superres.hpp  videoio.hpp
calib3d.hpp  features2d      highgui      imgproc        objdetect      photo               stitching      video         videostab
core         features2d.hpp  highgui.hpp  imgproc.hpp    objdetect.hpp  photo.hpp           stitching.hpp  video.hpp     videostab.hpp
core.hpp     flann           imgcodecs    ml             opencv.hpp     shape               superres       videoio
```

**Comment by vadimkantorov** [comment]
I've updated installation instructions. I also checked, it should now work with ffmpeg 3.1 and opencv 3.1.

You may use wigwam to install both (a tool i wrote).
