### ISSUE TITLE
B and I frames

### ISSUE THREAD

**Issue by sdruix** [vadimkantorov/mpegflow#13]
More than an issue is a question... Do you know any way for getting the B and I frames as they do in ffplay? Seems that I'm just getting the P ones.

Thanks,

Albert

**Comment by vadimkantorov** [comment]
Hey it's weird, it should still print info about B/I frames as well, since I don't do any explicit filtering. A very similar official FFmpeg's motion vectors example is here: https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/extract_mvs.c

**Comment by sdruix** [comment]
Thanks for your answer. And congrats for your investigation. I will look at that
