### ISSUE TITLE
Make vis fails

### ISSUE THREAD

**Issue by saulspatz** [vadimkantorov/mpegflow#14]
On Ubuntu 16.04, I followed your suggestions for the dependencies, and "make" created mpegflow just fine.  When I tried "make vis"  I got many, errors, as shown in the attched log file.
I made one change to the Makefile.  I did not have a static copy of libbz2 on my system, so I had to make one from the sources, and I added the resulting libbz2.a to my mpegflow folder.  Therefore, I added another -L path for the mpegflow target, but I changed nothing on the vis target.  (Actually, it looks like I should have, but we never got as far as the linker.)  Do you have any 
[vis.txt](https://github.com/vadimkantorov/mpegflow/files/822748/vis.txt)

idea what is causing this?

**Comment by vadimkantorov** [comment]
It seems to be a problem with OpenCV paths. In the log your OpenCV seems loaded from `/usr/local/include/opencv2/core.hpp` and not from `dependencies/include`. You need to check that your OpenCV is of recent version and to try to compile something like:
```cpp
#include <opencv2/core.hpp>
#include <iostream>

using namespace cv;

int main()
{
     cv::Mat m;
     std::cout << "Hello world" << std::endl;
}

**Comment by saulspatz** [comment]
I temporarily renamed the folder in /usr/local to avoid the conflict, but that didn't fix the problem.  The include files specified in vis.cpp don't exist in the dependencies folder.  There is no file
 dependencies/include/opencv2/core.hpp, although there is a file dependencies/include/opencv2/core/core.hpp.  Similarly, there is no file dependencies/include/openv2/improc.hpp, although there is a file dependencies/include/opencv2/improc/improc.hpp.  There are no files named videoio.hpp or imgcodecs.hpp anywhere in the dependencies folder.  I have files with these names on my system, but I have openCV 3.2 installed.  (I use the python interface to openCV and have never done any C++ work with it, so I don't know anything about this.) 

As I said earlier, I ran the shell scripts you supplied to make the dependencies folder.  Do you have any suggestions?

**Comment by vadimkantorov** [comment]
The build script might not be synchronized with the code (sorry for that). Could you try then using `#include <opencv2/core/core.hpp>` and such in `vis.cpp`?

You may also try removing OpenCV from the `dependencies` directory and try building against OpenCV 3.2 installed globally on your system. It could be I updated the source code to OpenCV 3, but not the build script.

Otherwise, I'll get to checking this, but in some days.

**Comment by saulspatz** [comment]
I note that all the libraries in the depe​ndencies folder are static .a
file, while all the ones on my system are .so files.  Do I have to change
the makefile in any way to account for this?  (Back in the days when I did
command line compiling, we didn't *have* dynamic libraries!)

**Comment by vadimkantorov** [comment]
I would suggest to either update the source code to match the headers you do get in `dependencies` or to install OpenCV that contains the needed headers. The binary should build fine statically.

The first problem to solve is definitely the headers.

**Comment by saulspatz** [comment]
I really appreciate your willingness to help, thanks.

I can't update the source code to match the headers in dependencies.  As I
tried to explain earlier, the videoio.hpp file and the imgcodecs.hpp file
don't appear anywhere in dependencies.  Oddly enough, they don't appear in
/usr/local/include either.  They are found in
~/opencv/modules/imgcodecs/include/opencv2/imgcodecs.hpp
and
~/opencv2/modules/videoio/include/opencv2/videoio.hpp

So it looks to me like I can try linking against openCV 3.2, but not
against openCV 2.4.

**Comment by saulspatz** [comment]
I successfully linked vis.ccp with openCV 3.2.  I changed the include directives to:

#include <opencv2/core/core.hpp>
#include <opencv2/videoio/videoio.hpp>
#include <opencv2/imgproc/imgproc.hpp>
#include <opencv2/imgcodecs/imgcodecs.hpp>
#include <opencv2/highgui/highgui.hpp>

I had to add `-lopencv_videoio` as a linker flag, and then I got a missing DSO error, so I had to add `-lopencv_imgcodecs` also.  

I've just checked that it built okay. I haven't run the examples yet.

**Comment by saulspatz** [comment]
Unfortunately, vis does not seem to be working.  When I run 
`mkdir -p vis_dump && ../mpegflow mpi_sintel_final_alley_1.avi | ../vis mpi_sintel_final_alley_1.avi vis_dump`  I get the message `Skipping frame N` for N=2,3,...49, and the only thing that shows up in vis_dump is a filename 00001.png, which appears to be the first frame of the video.  When I run the command with the `--occupancy` flag, I get a core dump, with the message `vis: vis.cpp:122: int main(int, const char**): Assertion `in.read(frame)' failed.`  

I guess this is a result of using openCV 3 instead of openCV 2.

**Comment by vadimkantorov** [comment]
Busy now with ICCV deadline. I'll take a look in one week or so.

I think it's a problem with OpenCV videoio. You may try to debug it.

**Comment by vadimkantorov** [comment]
If this code doesn't work and want to fight the bug, you may need to contact OpenCV developers (see https://github.com/opencv/opencv/issues/5088).

**Comment by ichraf** [comment]
Dear Vadim
Thank you for sharing your code. I had some problems with make vis. Finally i linked vis.ccp with openCV 3.2 and changed the Makefile INSTALLED_DEPS = -I/usr/local/include -L/usr/local/lib. . make vis worked. But as @saulspatz the example skipped the frames 2 to 49. 
i received this message : 
GStreamer: Error opening bin: Unrecoverable syntax error while parsing pipeline mpi_sintel_final_alley.avi
vis: vis.cpp:121: int main(int, const char**): Assertion `in.read(frame)' failed.
vis_mpeg_flow.sh: line 7: 30760 Broken pipe  ../mpegflow --occupancy mpi_sintel_final_alley_1.avi
     30761 Aborted        (core dumped) | ../vis mpi_sintel_final_alley.avi vis_dump

I tried to compile the example above but i got an error 
error: could not convert ‘in.cv::VideoCapture::operator>>(frame)’ from ‘cv::VideoCapture’ to ‘bool’
    while(in >> frame)

Thank you in advance.

**Comment by vadimkantorov** [comment]
Could you try `in.read(frame)` instead of `in >> frame`?

**Comment by ichraf** [comment]
I tried it in the basic code and it actually works fine. What have i to change in vis.cpp please?

**Comment by ichraf** [comment]
I  run mkdir -p examples/vis_dump && ./mpegflow examples/mpi_sintel_final_alley_1.avi | ./vis examples/mpi_sintel_final_alley_1.avi examples/vis_dump. It still skip all the frames but without any errors.
I added a line in the main function of vis.cpp to display flow.second from the function read.flow
inside the loop for 
fprintf(stderr,"flow second = %d.\n", int(flow.second));
It always returns -1

**Comment by vadimkantorov** [comment]
I've fixed the bug in vis, it should work now.

I've also fixed Makefile, it should now build as is with ffmpeg 3.1 and opencv 3.1 (and 3.2).

**Comment by saulspatz** [comment]
Works for me now.  Thanks for all your help.
