### ISSUE TITLE
Exe files flash

### ISSUE THREAD

**Issue by yuanchang200** [vadimkantorov/mpegflow#16]
Hi, thank you for the share. I built mpegflow and vis on Windows following your guide, and exe files are built successfully. But when I run the exe files, they just flash and I can't input command. I'm not sure what's going on.

**Comment by vadimkantorov** [comment]
You still need to run them from command line. Please let me know if it works well for you.

Envoyé de mon téléphone Windows 10

De : yuanchang200
Envoyé le :mardi 18 avril 2017 09:11
À : vadimkantorov/mpegflow
Cc : Subscribed
Objet :[vadimkantorov/mpegflow] Exe files flash (#16)

Hi, thank you for the share. I built mpegflow and vis on Windows following your guide, and exe files are built successfully. But when I run the exe files, they just flash and I can't input command. I'm not sure what's going on.

**Comment by yuanchang200** [comment]
Thank you for your reply. I run the command "mpegflow examples\mpi_sintel_final_alley_1.avi > examples\alley_1.txt", and there is a error message saying the mpegflow.exe stopped working, and there is nothing in the file alley_1.txt. I'm not sure if there was any problems during my building

**Comment by vadimkantorov** [comment]
Thanks for feedback. I will check it today.

**Comment by yuanchang200** [comment]
Thank you. Did you find the problem? Or it's just there is something wrong in my build

**Comment by EMCL** [comment]
hi,
i got this error when i try it on windows 7, 64 bit
$ ./mpegflow.cpp examples/mpi_sintel_final_alley_1.avi > examples/alley_1.txt
./mpegflow.cpp: line 6: $'\r': command not found
./mpegflow.cpp: line 7: extern: command not found
./mpegflow.cpp: line 8: $'{\r': command not found
./mpegflow.cpp: line 13: $'}\r': command not found
./mpegflow.cpp: line 14: $'\r': command not found
./mpegflow.cpp: line 19: $'\r': command not found
./mpegflow.cpp: line 20: using: command not found
./mpegflow.cpp: line 20: $'\r': command not found
./mpegflow.cpp: line 21: $'\r': command not found
./mpegflow.cpp: line 22: AVFrame*: command not found
./mpegflow.cpp: line 22: $'\r': command not found
./mpegflow.cpp: line 23: AVFormatContext*: command not found
./mpegflow.cpp: line 23: $'\r': command not found
./mpegflow.cpp: line 24: AVStream*: command not found
./mpegflow.cpp: line 24: $'\r': command not found
./mpegflow.cpp: line 25: int: command not found
./mpegflow.cpp: line 25: $'\r': command not found
./mpegflow.cpp: line 26: size_t: command not found
./mpegflow.cpp: line 26: $'\r': command not found
./mpegflow.cpp: line 27: $'\r': command not found
./mpegflow.cpp: line 28: bool: command not found
./mpegflow.cpp: line 28: $'\r': command not found
./mpegflow.cpp: line 29: const: command not found
./mpegflow.cpp: line 29: $'\r': command not found
./mpegflow.cpp: line 30: $'\r': command not found
./mpegflow.cpp: line 31: syntax error near unexpected token `('
'/mpegflow.cpp: line 31: `void ffmpeg_print_error(int err) // copied from cmdutils.c, originally called print_error

**Comment by vadimkantorov** [comment]
@EMCL You are trying to run the cpp source without compiling, it can't work. You need to build it using the Makefile first.
