### ISSUE TITLE
Make issue, cannot find -lavdevice

### ISSUE THREAD

**Issue by DBraun** [vadimkantorov/mpegflow#18]
I was able to run
`wigwam init && wigwam install opencv ffmpeg`
without any problems. However, make didn't work.

> machine@computer-ubuntu:~/Downloads/mpegflow-master$ make
g++ mpegflow.cpp -o mpegflow -O3 -D__STDC_CONSTANT_MACROS -lswscale -lavdevice -lavformat -lavcodec -lswresample -lavutil -lpthread -lbz2 -lz -lc -lrt -Idependencies/include -Ldependencies/lib
/usr/bin/ld: cannot find -lavdevice
collect2: error: ld returned 1 exit status
Makefile:6: recipe for target 'mpegflow' failed
make: *** [mpegflow] Error 1

Maybe this is helpful info too:

> machine@computer-ubuntu:~/Downloads/mpegflow-master/.wigwam/prefix/lib$ ls
libavcodec.a                   libopencv_ml.so
libavcodec.so                  libopencv_ml.so.3.2
libavcodec.so.57               libopencv_ml.so.3.2.0
libavcodec.so.57.48.101        libopencv_objdetect.so
libavdevice.a                  libopencv_objdetect.so.3.2
libavdevice.so                 libopencv_objdetect.so.3.2.0
libavdevice.so.57              libopencv_photo.so
libavdevice.so.57.0.101 

So it looks like the make command is looking inside /usr/bin/ld when I think it should look inside .wigwam/prefix/lib

I read a little here [https://stackoverflow.com/questions/16710047/usr-bin-ld-cannot-find-lnameofthelibrary](url), but my modifications to the make file were unsuccessful.

**Comment by vadimkantorov** [comment]
Please try `wigwam in` before launching `make`

**Comment by DBraun** [comment]
Thanks. The README.md is clearer now too.
