### ISSUE TITLE
Motion vectos values in I-frames

### ISSUE THREAD

**Issue by SerhanGul** [vadimkantorov/mpegflow#2]
When I extract the motion vectors (MV) from a video in the **matrix** form, I get for some I-frames non-zero MV values, whereas in the **raw** form, there are no recorded MVs (as expected, since I-frames are intra-coded and should, by definition, have no MVs). What is the source of this difference? 

In the matrix form, I-frames contain the flag **origin=interpolated** . Does that mean that these MVs I see for the I-frames are interpolated from those extracted for the P-frames?

**Comment by vadimkantorov** [comment]
Yes, exactly. They are interpolated from neighboring P-frames.
