### ISSUE TITLE
Mac OS / Linux install instructions

### ISSUE THREAD

**Issue by SamvitJ** [vadimkantorov/mpegflow#20]
Can you please include Mac OS / Linux install instructions?

**Comment by vadimkantorov** [comment]
I don't have a Mac, so can't test it, but the Makefile would likely work as is if you install a toolchain, FFmpeg and OpenCV using Homebrew. If you make it work, please let me know if any modifications to the Makefile are needed. Thanks!

**Comment by vadimkantorov** [comment]
@SamvitJ You mentioned in an email: "I was able to make the install work on Mac with a few modifications to the Makefile".

Could you provide back the modifications? I'd update the Makefile, so others have fewer issues.
