### ISSUE TITLE
Windows build issues

### ISSUE THREAD

**Issue by marius0210** [vadimkantorov/mpegflow#25]
i followed the steps to build on windows and i have this error

c:\Users\Gigabyte\Desktop\dependencies\mpegflow-master>nmake mpegflow.exe FFMPEG
_DIR=dependencies\ffmpeg-3.4-win64-dev\ffmpeg-3.4-win64-dev

Microsoft (R) Program Maintenance Utility Version 14.00.24210.0
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl mpegflow.cpp /OUT:mpegflow.exe /MT /EHsc /Idependencies\ffmpeg-3.4-wi
n64-dev\\include /link avcodec.lib avformat.lib avutil.lib swscale.lib swresampl
e.lib /LIBPATH:dependencies\ffmpeg-3.4-win64-dev\\lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.00.24215.1 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

cl : Command line warning D9035 : option 'Og' has been deprecated and will be re
moved in a future release
cl : Command line warning D9002 : ignoring unknown option '/OU'
cl : Command line warning D9002 : ignoring unknown option '/OT'
cl : Command line warning D9002 : ignoring unknown option '/O:'
cl : Command line warning D9002 : ignoring unknown option '/Om'
cl : Command line warning D9002 : ignoring unknown option '/Op'
cl : Command line warning D9002 : ignoring unknown option '/Oe'
cl : Command line warning D9002 : ignoring unknown option '/Of'
cl : Command line warning D9002 : ignoring unknown option '/Ol'
cl : Command line warning D9002 : ignoring unknown option '/Oo'
cl : Command line warning D9002 : ignoring unknown option '/Ow'
cl : Command line warning D9002 : ignoring unknown option '/O.'
cl : Command line warning D9002 : ignoring unknown option '/Oe'
cl : Command line warning D9002 : ignoring unknown option '/Oe'
mpegflow.cpp
mpegflow.cpp(9): fatal error C1083: Cannot open include file: 'libavcodec/avcode
c.h': No such file or directory
NMAKE : fatal error U1077: '"C:\Program Files (x86)\Microsoft Visual Studio 14.0
\VC\BIN\amd64\cl.EXE"' : return code '0x2'
Stop.

**Comment by vadimkantorov** [comment]
For warnings, do they disappear if you replace "/OUT" by "/Fe"?

For the error, does `libavcodec/avcodec.h` actually exist in your `dependencies\ffmpeg-3.4-wi
n64-dev\include`?

**Comment by marius0210** [comment]
I resolved the warnings and the error was caused from the incorrect path typing. Now I have another problem when i tried this example mpegflow examples\mpi_sintel_final_alley_1.avi > examples\alley_1.txt, mpegflow.exe has stopped working is the message. My ffmpeg version is 3.2 and latest version of opencv.

**Comment by vadimkantorov** [comment]
For warnings, is it the /Fe thing?

You may insert printf's everywhere to check what's failing. It's strange it's failing without a message.

**Comment by marius0210** [comment]
I deleted all and I started once again and with /Fe i have this message
c:\Users\MB\Desktop\dependencies>nmake mpegflow.exe FFMPEG_DIR=c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-dev\ffmpeg-3.2-win64-dev

Microsoft (R) Program Maintenance Utility Version 14.12.25830.2
Copyright (C) Microsoft Corporation.  All rights reserved.

        cl mpegflow.cpp /Fe:mpegflow.exe /MT /EHsc /Ic:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-dev\ffmpeg-3.2-win64-dev\include /link avcodec.lib avformat.lib avutil.lib swscale.lib swresample.lib /LIBPATH:c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-dev\ffmpeg-3.2-win64-dev\lib
Microsoft (R) C/C++ Optimizing Compiler Version 19.12.25830.2 for x64
Copyright (C) Microsoft Corporation.  All rights reserved.

mpegflow.cpp
mpegflow.cpp(254): warning C4477: 'printf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'int64_t'
mpegflow.cpp(254): note: consider using '%lld' in the format string
mpegflow.cpp(254): note: consider using '%Id' in the format string
mpegflow.cpp(254): note: consider using '%I64d' in the format string
mpegflow.cpp(292): warning C4477: 'printf' : format string '%ld' requires an argument of type 'long', but variadic argument 1 has type 'int64_t'
mpegflow.cpp(292): note: consider using '%lld' in the format string
mpegflow.cpp(292): note: consider using '%Id' in the format string
mpegflow.cpp(292): note: consider using '%I64d' in the format string
Microsoft (R) Incremental Linker Version 14.12.25830.2
Copyright (C) Microsoft Corporation.  All rights reserved.

/out:mpegflow.exe
avcodec.lib
avformat.lib
avutil.lib
swscale.lib
swresample.lib
/LIBPATH:c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-dev\ffmpeg-3.2-win64-dev\lib
mpegflow.obj
        for %I in (c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-shared\ffmpeg-3.2-win64-shared\bin\avutil-*.dll c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-shared\ffmpeg-3.2-win64-shared\bin\avformat-*.dll c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-shared\ffmpeg-3.2-win64-shared\bin\avcodec-*.dll c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-shared\ffmpeg-3.2-win64-shared\bin\swresample-*.dll) do copy %I c:\Users\MB\Desktop\dependencies

c:\Users\MB\Desktop\dependencies>copy c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-shared\ffmpeg-3.2-win64-shared\bin\avutil-55.dll c:\Users\MB\Desktop\dependencies
        1 file(s) copied.

c:\Users\MB\Desktop\dependencies>copy c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-shared\ffmpeg-3.2-win64-shared\bin\avformat-57.dll c:\Users\MB\Desktop\dependencies
        1 file(s) copied.

c:\Users\MB\Desktop\dependencies>copy c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-shared\ffmpeg-3.2-win64-shared\bin\avcodec-57.dll c:\Users\MB\Desktop\dependencies
        1 file(s) copied.

c:\Users\MB\Desktop\dependencies>copy c:\Users\MB\Desktop\dependencies\ffmpeg-3.2-win64-shared\ffmpeg-3.2-win64-shared\bin\swresample-2.dll c:\Users\MB\Desktop\dependencies
        1 file(s) copied.

**Comment by vadimkantorov** [comment]
Thanks for trying this. It then still crashes?

Could you also try to compile it with `pts=%lld` in line 254 and line 292? This should suppress the warnings.

**Comment by marius0210** [comment]
Yes it still crashes, i moved to linux and i tried to build, mpeg is ok but with vis i received this error

root@mb-ThinkPad-L512:/home/mb/mpegflow# /\ $ make vis
g++ vis.cpp -o vis -O3 -D__STDC_CONSTANT_MACROS -lopencv_highgui -lopencv_videoio -lopencv_imgproc -lopencv_imgcodecs -lopencv_core -lpng -lswscale -lavdevice -lavformat -lavcodec -lswresample -lavutil -lpthread -lbz2 -lz -lc -lrt -Idependencies/include -Ldependencies/lib 
/usr/bin/ld: cannot find -lpng
collect2: error: ld returned 1 exit status
Makefile:9: recipe for target 'vis' failed
make: *** [vis] Error 1

**Comment by vadimkantorov** [comment]
The error seems to indicate that you don't have shared libpng discoverable. You may want to install libpng-dev or something similar for your system.

**Comment by marius0210** [comment]
Thanks, I installed libpng-dev and now all works in ubuntu linux.
