### ISSUE TITLE
Comilation error

### ISSUE THREAD

**Issue by jishnujayakumar** [vadimkantorov/mpegflow#29]
Used => g++ -o mv mpegflow.cpp `pkg-config --cflags --libs -L/opt/dev-tools-sources/ffmpeg/lib -I/opt/dev-tools-sources/ffmpeg/include/ -o mp mpegflow.cpp -lavcodec -lavformat -lavutil -lavdevice -lswresample -lswscale -lm -lva -lpthread -lvorbis -lvpx -lopus -lz -lpostproc -ldl -lfdk-aac -lmp3lame -lvorbisenc -lvorbisfile -lx264 -ltheora -ltheoraenc -ltheoradec -ldl -lrt -lx265` for compiling mpegflow.cpp

But got the following error.

Unknown option -L/opt/dev-tools-sources/ffmpeg/lib
mpegflow.cpp: In member function ‘void FrameInfo::PrintIfNotPrinted()’:
mpegflow.cpp:254:203: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 2 has type ‘int64_t {aka long int}’ [-Wformat=]
 frame_index=%d pict_type=%c output_type=arranged shape=%zux%zu origin=%s\n", Pts - FirstPts, FrameIndex, PictType, (ARG_OUTPUT_OCCUPANCY ? 3 : 2) * Shape.first, Shape.second, Origin);
                                                                                                                                                                                      ^
mpegflow.cpp: In function ‘void output_vectors_raw(int, int64_t, char, std::vector<AVMotionVector>&)’:
mpegflow.cpp:292:128: warning: format ‘%lld’ expects argument of type ‘long long int’, but argument 2 has type ‘int64_t {aka long int}’ [-Wformat=]
  printf("# pts=%lld frame_index=%d pict_type=%c output_type=raw shape=%zux4\n", pts, frameIndex, pictType, motionVectors.size());
                                                                                                                                ^
/tmp/ccEvt7q2.o: In function `ffmpeg_print_error(int)':
mpegflow.cpp:(.text+0x46): undefined reference to `av_strerror'
mpegflow.cpp:(.text+0x86): undefined reference to `av_log'
/tmp/ccEvt7q2.o: In function `ffmpeg_init()':
mpegflow.cpp:(.text+0xd2): undefined reference to `av_register_all'
mpegflow.cpp:(.text+0xe7): undefined reference to `av_log_set_level'
mpegflow.cpp:(.text+0xf1): undefined reference to `av_log_set_callback'
mpegflow.cpp:(.text+0xf6): undefined reference to `av_frame_alloc'
mpegflow.cpp:(.text+0x102): undefined reference to `avformat_alloc_context'
mpegflow.cpp:(.text+0x138): undefined reference to `avformat_open_input'
mpegflow.cpp:(.text+0x1cb): undefined reference to `avformat_find_stream_info'
mpegflow.cpp:(.text+0x2b3): undefined reference to `avcodec_find_decoder'
mpegflow.cpp:(.text+0x2da): undefined reference to `av_dict_set'
mpegflow.cpp:(.text+0x2f8): undefined reference to `avcodec_open2'
/tmp/ccEvt7q2.o: In function `process_frame(AVPacket*)':
mpegflow.cpp:(.text+0x55a): undefined reference to `av_frame_unref'
mpegflow.cpp:(.text+0x583): undefined reference to `avcodec_decode_video2'
/tmp/ccEvt7q2.o: In function `read_packets()':
mpegflow.cpp:(.text+0x62c): undefined reference to `av_packet_unref'
mpegflow.cpp:(.text+0x647): undefined reference to `av_read_frame'
mpegflow.cpp:(.text+0x721): undefined reference to `av_packet_unref'
/tmp/ccEvt7q2.o: In function `read_frame(long&, char&, std::vector<AVMotionVector, std::allocator<AVMotionVector> >&)':
mpegflow.cpp:(.text+0x786): undefined reference to `av_get_picture_type_char'
mpegflow.cpp:(.text+0x80e): undefined reference to `av_frame_get_side_data'
mpegflow.cpp:(.text+0x83a): undefined reference to `av_frame_get_side_data'
collect2: error: ld returned 1 exit status

**Comment by vadimkantorov** [comment]
Fixed
