### ISSUE TITLE
Does mpegflow work for mp4 files as well? 

### ISSUE THREAD

**Issue by jishnujayakumar** [vadimkantorov/mpegflow#30]
I am asking this because when I tried to run a .mp4 file using the following command 
./mpegflow examples/deepsort-easy1.mp4 > examples/deepsort-easy1.mp4.txt 

I got the following error.

terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc
Aborted (core dumped)

**Comment by vadimkantorov** [comment]
There is an unfixed out-of-memory bug related to insertion of dummy frames (please search in Issues). You may comment out dummy frame insertion, it may help.

If it doesn't, unfortunately, I'm unable to assist further at this point, I'm not actively maintaining the project anymore.

**Comment by jishnujayakumar** [comment]
Cool @vadimkantorov.
Yeah, I found that exact stuff in the issues.
Some frames are skipped.
But I think it won't cause any issue for my task.
