### ISSUE TITLE
Is there a way to use it with a h264 stream

### ISSUE THREAD

**Issue by vedmant** [vadimkantorov/mpegflow#32]
Hi, I have a raspberry pi camera, and I've written small nodejs app to capture h264 stream and split it to different destinations like browser web socket when requested, save to file, etc... I wan't also to pipe this stream to your app and get back live motion vectors to detect motion in the video, is this possible?

Thanks!

**Comment by vadimkantorov** [comment]
It won't work out of the box, but you can check out mpegflow's code and write your own ffmpeg code working with a stream.

`mpegflow` is really just a thin wrapper around ffmpeg's decoding APIs. The desktop ffmpeg's h.264 decoder can dump decoded motion vectors.

Recent versions of ffmpeg also include some command line switch (sth like `+extract_mvs`, but one needs to search online) for doing that. Maybe you can pipe to ffmpeg directly, and dump the vectors from ffmpeg.

Good luck!

**Comment by vedmant** [comment]
Thanks! I'm not a C++ dev, so it will take more time to understand sources, I'll check out ffmpeg.
