### ISSUE TITLE
Output values

### ISSUE THREAD

**Issue by ssulun** [vadimkantorov/mpegflow#34]
I'm using videos encoded with ffmpeg x264 in default mode (subpixel motion estimation enabled, motion estimation range = 24). I have two questions about the output values of raw vectors.

Firstly, all values are integers, I expected noninteger values because of subpixel motion estimation. Secondly, there are values much larger than the motion estimation range.

**Comment by vadimkantorov** [comment]
Please consider **mpegflow** as an example of working with FFmpeg, and its AVMotionVector structure:  https://github.com/vadimkantorov/mpegflow/blob/master/mpegflow.cpp#L295

You can modify the relevant parts working with AVMotionVector, and possibly to post-process it differently. An analagous and newer tool is https://github.com/FFmpeg/FFmpeg/blob/master/doc/examples/extract_mvs.c

For motion scale, you may want to use `mv.motion_scale` (which i don't use) - https://github.com/FFmpeg/FFmpeg/blob/a0ac49e38ee1d1011c394d7be67d0f08b2281526/libavcodec/mpegutils.c#L32

Though ffmpeg itself doesn't seem to use it during motion vector visualization: https://github.com/FFmpeg/FFmpeg/blob/a0ac49e38ee1d1011c394d7be67d0f08b2281526/libavfilter/vf_codecview.c#L246

Good luck!
