### ISSUE TITLE
MPI Sintel data set in AVI format video

### ISSUE THREAD

**Issue by sebawsky** [vadimkantorov/mpegflow#38]
Hello, I would like to request your help. I can extract the Motion Vector without problems from a video but when I create the video from the images the Motion Vector that I extract have problems, this does not happen with the video that you share (mpi_sintel_final_alley_1.avi). Could you share the videos of the MPI Sintel database that you generated, I would greatly appreciate it. Thank you

**Comment by vadimkantorov** [comment]
Sorry, I don't have those files anymore. Feel free to use extract_mvs from FFmpeg instead of this project. Please consider this codebase as a mere primer of FFmpeg usage.

**Comment by vadimkantorov** [comment]
I recommend you first use FFmpeg's utility extract_mvs on your files. If it doesn't work, then the problem is most likely in FFmpeg
