### ISSUE TITLE
Black frames for UCF101 videos

### ISSUE THREAD

**Issue by kirillgavrilyuk** [vadimkantorov/mpegflow#4]
I am currently trying to use your code for processing UCF101 dataset. I am using mpegflow binary for this task and I have found two problems:

1. For almost all videos in the dataset I have black frames in the beginning and in the end of video.
2. For  around 3000 out of 13320 videos mpegflow produces black frames in the middle of the video. One of these videos is ParallelBars/v_ParallelBars_g06_c04.avi. The output of mpegflow run is:

[0;36m[mpeg4 @ 0x240d300] [0mVideo uses a non-standard and wasteful way to store B-frames ('packed B-frames'). Consider using the mpeg4_unpack_bframes bitstream filter to fix it.
Skipping frame 6 (frame with pts 5 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 44 DC, 44 AC, 44 MV errors in B frame
Skipping frame 8 (frame with pts 6 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 11 (frame with pts 8 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0mconcealing 27 DC, 27 AC, 27 MV errors in B frame
Skipping frame 15 (frame with pts 11 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 47 DC, 47 AC, 47 MV errors in B frame
Skipping frame 20 (frame with pts 15 already processed).
[0;36m[mpeg4 @ 0x240d300] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 26 (frame with pts 20 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 47 DC, 47 AC, 47 MV errors in B frame
Skipping frame 28 (frame with pts 21 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 31 (frame with pts 23 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0mconcealing 22 DC, 22 AC, 22 MV errors in B frame
Skipping frame 35 (frame with pts 26 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 47 DC, 47 AC, 47 MV errors in B frame
Skipping frame 40 (frame with pts 30 already processed).
[0;36m[mpeg4 @ 0x240d300] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 46 (frame with pts 35 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 44 DC, 44 AC, 44 MV errors in B frame
Skipping frame 48 (frame with pts 36 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 51 (frame with pts 38 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mslice end not reached but screenspace end (46 left 5C3523, score= -38)
[0m[0;36m[mpeg4 @ 0x23fd0c0] [0mconcealing 300 DC, 300 AC, 300 MV errors in B frame
Skipping frame 55 (frame with pts 41 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 41 DC, 41 AC, 41 MV errors in B frame
Skipping frame 60 (frame with pts 45 already processed).
[0;36m[mpeg4 @ 0x240d300] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 66 (frame with pts 50 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 43 DC, 43 AC, 43 MV errors in B frame
Skipping frame 68 (frame with pts 51 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 71 (frame with pts 53 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0mconcealing 21 DC, 21 AC, 21 MV errors in B frame
Skipping frame 75 (frame with pts 56 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 42 DC, 42 AC, 42 MV errors in B frame
Skipping frame 80 (frame with pts 60 already processed).
[0;36m[mpeg4 @ 0x240d300] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 86 (frame with pts 65 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 40 DC, 40 AC, 40 MV errors in B frame
Skipping frame 88 (frame with pts 66 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 91 (frame with pts 68 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mslice end not reached but screenspace end (10 left 4EC000, score= -63)
[0m[0;36m[mpeg4 @ 0x23fd0c0] [0mconcealing 300 DC, 300 AC, 300 MV errors in B frame
Skipping frame 95 (frame with pts 71 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 40 DC, 40 AC, 40 MV errors in B frame
Skipping frame 100 (frame with pts 75 already processed).
[0;36m[mpeg4 @ 0x240d300] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 106 (frame with pts 80 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 40 DC, 40 AC, 40 MV errors in B frame
Skipping frame 108 (frame with pts 81 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 111 (frame with pts 83 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0mconcealing 21 DC, 21 AC, 21 MV errors in B frame
Skipping frame 115 (frame with pts 86 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 42 DC, 42 AC, 42 MV errors in B frame
Skipping frame 120 (frame with pts 90 already processed).
[0;36m[mpeg4 @ 0x240d300] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 126 (frame with pts 95 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 43 DC, 43 AC, 43 MV errors in B frame
Skipping frame 128 (frame with pts 96 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 131 (frame with pts 98 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0mconcealing 23 DC, 23 AC, 23 MV errors in B frame
Skipping frame 135 (frame with pts 101 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 40 DC, 40 AC, 40 MV errors in B frame
Skipping frame 140 (frame with pts 105 already processed).
[0;36m[mpeg4 @ 0x240d300] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 146 (frame with pts 110 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 40 DC, 40 AC, 40 MV errors in B frame
Skipping frame 148 (frame with pts 111 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 151 (frame with pts 113 already processed).
Skipping frame 155 (frame with pts 116 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 40 DC, 40 AC, 40 MV errors in B frame
Skipping frame 160 (frame with pts 120 already processed).
[0;36m[mpeg4 @ 0x240d300] [0m[1;31mwarning: first frame is no keyframe
[0mSkipping frame 166 (frame with pts 125 already processed).
[0;36m[mpeg4 @ 0x2410520] [0mconcealing 40 DC, 40 AC, 40 MV errors in B frame
Skipping frame 168 (frame with pts 126 already processed).
[0;36m[mpeg4 @ 0x23fd0c0] [0m[1;31mwarning: first frame is no keyframe
[0mComputing mpegflow was completed.

Did you have the same problems with UCF50 that you used in your paper? How to deal with these problems?

Thanks in advance.

**Comment by vadimkantorov** [comment]
Hi, yes, I think I've had similar issues. If I remember well, I've recoded the original videos using libxvid, similar to what I did with HMDB51 here (https://github.com/vadimkantorov/cvpr2014/blob/master/repro/hmdb-51/Makefile), but I don't remember for sure.
