### ISSUE TITLE
Vis error

### ISSUE THREAD

**Issue by aurotripathy** [vadimkantorov/mpegflow#6]
Please forgive me for re-opening this tickets again, #1 .

The previous guidance was to go back to FFmpeg 1.1.2. 

Is this still the only way to try for a resolution?

It would be great to make this work on more recent version of avconv/ffmpeg.

**Comment by vadimkantorov** [comment]
Essentially it was a problem with OpenCV's bindings to ffmpeg. I'll check if it's working with a recent version of OpenCV.

**Comment by aurotripathy** [comment]
Thank you, Vadim. If you need me to test any code-drop, I will gladly do it.

**Comment by vadimkantorov** [comment]
Hey. I just fixed a bug in vis. If you are still on it, please let me know if it works for you now.
