### ISSUE TITLE
cannot find -lswresample

### ISSUE THREAD

**Issue by amlandas78** [vadimkantorov/mpegflow#8]
Hi, 
While installing the dependencies (opencv 2.4.11), I faced the error message: 
/usr/bin/ld: cannot find -lswresample
/usr/bin/ld: cannot find -lswresample
collect2: error: ld returned 1 exit status
Can you please help me with this?

**Comment by vadimkantorov** [comment]
Does your ffmpeg ship with the swresample library? (in older versions of ffmpeg it was named differently) You may want to check it by running: `$ locate libswresample.so`.

**Comment by amlandas78** [comment]
libswresample.so is there. Should I change it to libswresample.so? If yes, where should I change it? Thank you @vadimkantorov for the fast reply.

**Comment by vadimkantorov** [comment]
You could change it to libswresample.so, yes. Though, IIRC, the build script tries to link statically with ffmpeg. You may check for existence of libswresample.a.

**Comment by vadimkantorov** [comment]
Hi. I updated installation instructions. Please let me know if it now works for you.
