### ISSUE TITLE
libswscale #error in execution of opencv 2.4.11 install shell script

### ISSUE THREAD

**Issue by mihir-thakkar** [vadimkantorov/mpegflow#9]
While installing OpenCV, I get the following error.

"libswscale is necessary to build the newer OpenCV ffmpeg wrapper"
    #error "libswscale is necessary to build the newer OpenCV ffmpeg wrapper"
     ^

How can I resolve this? Note that libswscale is present in the ffmpeg folder.

**Comment by vadimkantorov** [comment]
Does the last answer https://github.com/opencv/opencv/issues/5930 help?

I'll move the code to OpenCV 3.0, the problem should go away.

**Comment by mihir-thakkar** [comment]
Nope, this did not solve the issue.

**Comment by vadimkantorov** [comment]
It seems then it's an OpenCV, ffmpeg, pkg-config-related issue. I'll try upgrading mpegflow to OpenCV 3.x when I have time.

For time being, I'd suggest you also migrate to OpenCV 3.x if you can afford it. Otherwise keep investigating the issue, unfortunately, I could not help further on this one.
